---
title: "Notes and planning"
author: "Aidan O'Hara"
date: "2023-05-14"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

13 weeks and 92 days until august 15th

### Macine Learning
Review 679 for machine learning exercise, see how TNum might be involved.

### Data exploration with an eye for emergent structure
Data ingestion, EDA protocols and procedures and TNum

### Project Management for the C-Suite
You could put together project management about collecting data for presentation and education, a notch above excel for in-office data organization.
More like Jira, specifically project management

### Data base idea
You can use chatGPT to come up with almost names for true numbers and database.

### Summer Goals
How do we get to money by the Fall, or early next year?
In the meantime, with our spare time, put together something about data collection and our other examples.
Meetings Tuesday night after 6pm

### Posts from Allen

### tnum website

### Collaborative tnum story project

### Pool a list of prospects, corps, comps, etc
## people to talk to and their value propositions
# Restraunts
my friend the brewer, restraunts probably don't have the capitol though. 

## what are our pitches

### Demonstration of "What tnum looks like?"

### What do we want to accomplish this summer!

### Chris Madrid and Allison Turner

### Potential Applications

#### Data exploration with an eye for emergent structure
Engineers and Scientists for "desktop" data
- adhoc databases
- calculation management
- numbers management is more difficult and important
- units, provenance, and more...
- hard to sell
- why not? despite the head nods. 
- Angel investor said it was because not enough funding.
- Before it was problematic that you'd have to use a server for the hosting, not comfy for the engineers.
Finance and Merger Aquisition people, also, not really, they are different markets for the desktop data stuff
This one also sort of umbrellas over Machine learning transparency, they are engineers and scientists developing those models.

IT Data integration
SPAWAR data integration
- data in motion - data out of the database
- data at rest - data in the database
- data in motion, goes to applications, down pipelines, cruising around
- tnum fits here because with trad db you need a schema that will eventually need to be replaced, loosing the investment in data base mounted applications.
- pedigree and provenance, wherein tnums have tags and history that describe the number.

Security incidents and quality control

Center for Industrial information



### Work Plan
Work with Srdjan to do play things and get a feel for how true numbers works.
